from CustomerAc.Exercise_sdk import algorithm_1
from CustomerAc.Exercise_sdk import algorithm_2
from CustomerAc.Exercise_sdk import algorithm_3
from CustomerAc.Exercise_sdk import algorithm_4
from CustomerAc.Exercise_sdk import algorithm_5
from CustomerAc.Exercise_sdk import algorithm_6
from CustomerAc.Exercise_sdk import algorithm_7
from CustomerAc.Exercise_sdk import algorithm_8
from CustomerAc.Exercise_sdk import algorithm_9
from CustomerAc.Exercise_sdk import algorithm_10
from CustomerAc.Exercise_sdk import testsdk